import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Header } from "../components/header";
import { Footer } from "../components/footer";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable}
        antialiased
        overflow-y-scroll
        bg-[url('/background.webp')]
        bg-cover
        bg-no-repeat
        bg-fixed
        bg-top
        `}
      >
        <div className="max-w-[780px] p-4 md:p-10 mx-auto bg-background min-h-screen">
          <Header></Header>
          {children}
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
